Repository DeveloperAcademy-POSTECH/2025-SSG-M2, pull requests merged in 2025-08, with the labels that each got.

#52 Nyx/Error Handling
  닉스/Swift 문법/Error Handling.md
Labels: 📝학습완료, 🤔리뷰 기다리는 중

#57 Sena/Stored Properties
  세나/Swift 문법/Stored Properties (저장 프로퍼티).md
  세나/Swift 문법/프로퍼티.md
Labels: 📝학습완료, 🤔리뷰 기다리는 중, 💻Swift 문법 학습

#58 kwangro/ios-interview-54
  광로/iOS InterView 질문 정리.md
Labels: 📝학습완료, 🤔리뷰 기다리는 중

#65 Nyx/SpriteKit
  닉스/iOS 기능/SpriteKit.md
Labels: 🛠️iOS 기술 학습

#68 Kwangro/클린 아키텍쳐 Presentation 1편
  광로/이미지/Pasted image 20250724195726.png
  광로/이미지/Pasted image 20250724201243.png
  광로/이미지/Pasted image 20250724201536.png
  광로/이미지/Pasted image 20250724212335.png
  광로/이미지/Pasted image 20250724212400.png
  광로/클린 아키텍쳐 (Clean Architecture).md
Labels: 🚧아직 작성 중, 🛠️iOS 기술 학습

#73 Ethan/Cloudkit
  이든/iOS 기능/CloudKit.md
Labels: 📝학습완료

#74 Nyx/Protocol과 Delegate
  닉스/Swift 문법/Protocol & Delegate.md
Labels: 🤔리뷰 기다리는 중, 💻Swift 문법 학습
